#**
#* 2007-2019 Frédéric BENOIST
#*
#* NOTICE OF LICENSE
#*
#* This source file is subject to the Academic Free License (AFL 3.0)
#* that is bundled with this package in the file LICENSE.txt.
#* It is also available through the world-wide-web at this URL:
#* http://opensource.org/licenses/afl-3.0.php
#* If you did not receive a copy of the license and are unable to
#* obtain it through the world-wide-web, please send an email
#* to license@prestashop.com so we can send you a copy immediately.
#*
#*  @author    Frédéric BENOIST
#*  @copyright 2013-2019 Frédéric BENOIST <https://www.fbenoist.com/>
#*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
#*/

parameters:
    fbsample_botraining_legacy_ctrl_title: "Sample value in module services.yml"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    mycommand:
        class: FBenoist\FbSample_BoTraining\Command\MyCommand
        public: true
        tags:
            - { name: 'console.command' }

    product_repository:
        class: FBenoist\FbSample_BoTraining\Repository\ProductRepository
        arguments: ['@doctrine.dbal.default_connection', '%database_prefix%']
